### PR TITLE
2.0.19

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — DISMISSED** [review]

**Comment by sbc100** [comment]
Also added LTO build so folks can try it out.

**Comment by kripken** [comment]
Aside from the test failures this lgtm to land. (Even before the LTO one finishes all tests - we can remove it later if we want.)

**Comment by kripken** [comment]
Actually, are the lto and non-lto versions identical in the DEPS they are built from?

**Comment by sbc100** [comment]
> Actually, are the lto and non-lto versions identical in the DEPS they are built from?

Yup that is my understanding

**Comment by kripken** [comment]
Yes, I verified they are identical now, sorry. I was misreading it before.

**Pull request merged**
