### PR TITLE
Provide "executable" in wasm_cc_binary's DefaultInfo.

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by PiotrSikora** [comment]
This is needed to allow custom rules and/or transitions on top of `wasm_cc_binary` (e.g. to workaround #972).

It's debatable whether `.wasm` is the correct `executable` target for non-standalone Wasm builds, but we don't have a way to differentiate those in `wasm_cc_binary`, and considering that this attribute isn't exported now, it shouldn't break anything.

cc @trybka

**Comment by trybka** [comment]
LGTM.

@walkingeyerobot or @sbc100 can review / import

**Review by sbc100 — APPROVED** [review]
rubberstamp lgtm

**Comment by bkotsopoulossc** [comment]
Can you explain what this helps accomplish? I’m not quite following

**Comment by PiotrSikora** [comment]
This allows accessing `.wasm` module via [`DefaultInfo.files_to_run.executable`](https://bazel.build/rules/lib/DefaultInfo#files_to_run), and using `wasm_cc_binary` as an input in another rule.

I'm using this to force extra transitions in [`proxy_wasm_cc_binary`](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/blob/05862acc58782f108d2193a7f2db461bb6601fdd/bazel/defs.bzl).

**Pull request merged**
