### PR TITLE
2.0.24

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
Since Derek is OOO I suggest we just do a non-LTO release for now.  We can add an LTO version of this release later.. and make it the default in a future release?

**Review by kripken — APPROVED** [review]
Plan sgtm.

**Comment by kripken** [comment]
However, looking at the roller, the emscripten one seems to be broken?

**Comment by sbc100** [comment]
> However, looking at the roller, the emscripten one seems to be broken?

Does that matter?  It shouldn't stop use releases should it?

**Comment by sbc100** [comment]
Actually maybe if we are 17 behind that is a lot.. let me check.

**Comment by kripken** [comment]
It doesn't block in general, yeah, but weren't there changes you wanted to roll in for the release? Or did they make it before the breakage?

**Comment by sbc100** [comment]
Uploaded new revision now that the roller is passing again

**Comment by kripken** [comment]
It looks like the asan test suite started to fail right on that commit, so perhaps we should verify if that is a test suite problem or something more serious first? I can take a look in a bit.

**Comment by sbc100** [comment]
Looks like it was #14399 that starting asan.test_utf8_textdecoder failing.

**Comment by sbc100** [comment]
If its just a bug in the test I suggest we go ahead with this release.. if its a bug in the library code I guess we need to wait for a fix.

**Comment by kripken** [comment]
I verified it is a bug in the test. The bug pre-existed before my commit, but the commit unsurfaced it. Anyhow, lgtm for this PR, nothing to worry about, there is no library code bug.

**Pull request merged**
