### PR TITLE
Add release reviewers to release creation PRs

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
testing @emscripten-core/release-reviewers

**Comment by aheejin** [comment]
Nice! Is this meant to just cc the mailing list? Or is adding it to the actual reviewer the next step?

**Comment by dschuff** [comment]
I think github is supposed to notify each member of the team, not the bot account.

**Review by aheejin — APPROVED** [review]

**Comment by dschuff** [comment]
Oh and yes, this PR is supposed to add actual reviewers.

**Comment by dschuff** [comment]
I'll test this after the real PR comes through, should just be a few minutes from now.

**Review by sbc100 — APPROVED** [review]
Nice!

**Comment by dschuff** [comment]
I think it's working now. interesting that the action will update an existing PR if one exists rather than creating a new one.

**Comment by dschuff** [comment]
@walkingeyerobot it seems unrelated to this PR (which doesn't affect any tests), but the test-bazel-windows build seems to be failing.

**Pull request merged**
