### PR TITLE
3.1.2

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — COMMENTED** [review]
Looks like the "build binaryen" phase failed in the LTO build on CI, both on mac and on the test-suites bot. That's odd... and it means we lack some coverage. Should we re-run?

**Comment by sbc100** [comment]
I don't see any failure on the mac builder... the failure on the test-suites we have seen before.  I had thought it was a flake... but now I think perhaps it relates to the LTO build?   In any case I don't think it should block the release.. its not new an I don't think its means that any of our tests are failing.. the test-suite builder is green both before and after.

**Comment by sbc100** [comment]
@dschuff WDYT could cause this: https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8824503322313428673/+/u/Build_Binaryen/stdout

**Comment by kripken** [comment]
It is kind of worrying if we have LTO-specific breakage on CI, though, since it's all the testing we have of that mode. I do agree it's unlikely to be a real problem though if it's not new.

**Comment by sbc100** [comment]
> It is kind of worrying if we have LTO-specific breakage on CI, though, since it's all the testing we have of that mode. I do agree it's unlikely to be a real problem though if it's not new.

But its not a new problem.. its happened because.. and its also unrelated to the usage of the SDK, its a failure to build binaryen at all.  I don't see how that could effect users..

But mostly, the main argument is that the same issue was present for previous releases.

**Comment by sbc100** [comment]
Here is the exact same failure for the current (3.1.1) release: https://ci.chromium.org/ui/p/emscripten-releases/builders/ci/linux-test-suites/b8825598267549107185/overview

**Comment by kripken** [comment]
Yes, users don't build binaryen, but without CI building it we can't test, so we are not actually validating the build, at least in some configs, before sending it out to users.

**Comment by sbc100** [comment]
> Yes, users don't build binaryen, but without CI building it we can't test, so we are not actually validating the build, at least in some configs, before sending it out to users.

Have we historically required the test-suites builder to be green to do a release?   We know the test-suites builder is actually green (since it was green both before and after the LTO) build.

We have all the normal coverage from the three main builders, plus we know that the test-suites builder is generally green right now.  So there is a very very slim chance that there is an LTO-only bug that *only* shows up on the tests-suites builder.   But we have no evidence to suggest there is such a bug, and as far as I know we have never actually seen an LTO-only at all.  So it seems rather overly-conservative to think there is one..

If you feel strongly we can just drop the LTO build for a release or two until this is fixed?

**Comment by kripken** [comment]
To be clear, I'm not saying we should block the release. It may be ok to continue.

> Have we historically required the test-suites builder to be green to do a release?

Yeah, we haven't. Maybe it's excessive.

The Mac build is still running though, we should at least wait for that I think, https://ci.chromium.org/ui/p/emscripten-releases/builders/ci/mac/b8824503322810676161/overview

> We know the test-suites builder is actually green (since it was green both before and after the LTO) build.

But maybe it is broken specifically only on LTO? That is what worries me. I realize it's not likely, but we are blind to a possible problem here. You are right that LTO-only errors are very unlikely, but OTOH we only test LTO when we make a release, it's already a sparsely-tested mode...

Again, I'm not saying to block the release. If both are you are comfortable, sgtm.

**Comment by sbc100** [comment]
Blocked on #974

**Comment by dschuff** [comment]
Here's a fix for the LTO issue: https://chromium-review.googlesource.com/c/emscripten-releases/+/3402523

**Comment by dschuff** [comment]
Don't forget that LTO-optimized host binaries are unrelated to building LTO-optimized wasm binaries. All of the tests that the non-testsuite bots run do test that the LTO-optimized Binaryen works.

**Comment by sbc100** [comment]
Thanks derek!   If that change lands and is green (and the mac build finishes) I think we should land this change on the assumption that we found an fixes the issue.   Does that make sense to you both too?

**Comment by dschuff** [comment]
and yes, I don't think this needs to block the release. If there were a problem with the LTO build of Binaryen, it would have to be something that causes Binaryen to fail to work, only in some code that is exercised by tests that run on the testsuite bot, and it would have to be caused by building with LTO itself (since the actual Binaryen codebase has already been tested in other commits)

**Comment by dschuff** [comment]
Unfortunately the above change won't actually test the LTO build in the commit where it lands, because that commit will not be an update to DEPS.tagged-release. I did test it locally though.

**Comment by kripken** [comment]
@sbc100 sgtm

**Review by kripken — APPROVED** [review]

**Comment by sbc100** [comment]
It looks like we are going with non-LTO for the test-suites bot for now: https://chromium-review.googlesource.com/c/emscripten-releases/+/3405443

Given that, ok to go ahead and land this change?

**Review by dschuff — APPROVED** [review]

**Review by kripken — APPROVED** [review]

**Comment by kleisauke** [comment]
It looks like the 3.1.2 tag is missing from https://github.com/emscripten-core/emsdk/tags (as a result, the `emscripten/emsdk:3.1.2` Docker image has not yet been published).

**Comment by sbc100** [comment]
Fixes!  thanks.

**Pull request merged**
