### PR TITLE
Update XCode version on CircleCI

### PR DESCRIPTION
**Pull request by dschuff**
12.2 is being deprecated.

### CODE REVIEW

**Review by kripken — APPROVED** [review]

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
It looks like the test failure occurs when trying to run `emcc` from an old version of emscripten (`sdk-upstream-5c776e6a91c0cb8edafca16a652ee1ee48f4f6d2`) where emcc relies on `python` being the PATH.. but its is not in the PATH which I suppose means:

a) we were relying on the previous behaviour of the 12.2.0 to provide `python` in the path.
b) emcc was not being run using the python provided by emsdk.

Maybe its time to drop support for these older version of emsdk?

**Comment by sbc100** [comment]
I imagine what happened is that the new image contains a newer version of macOS without /usr/bin/python?

**Comment by sbc100** [comment]
https://macmule.com/2022/01/29/macos-monterey-12-3-will-remove-python-2-7-usr-bin-python/

**Comment by dschuff** [comment]
Yeah, that could very well be. Given that emscripten only supports py3 now, I guess it kind of makes sense for us to stop testing the ancient versions on CI. If something breaks we could always make the recommendation to use an old emsdk to install an old emscripten.

**Comment by sbc100** [comment]
Can you try adding `python` to the `brew install` step?

**Comment by dschuff** [comment]
sure, I guess it needs to be 'python' (not 'python2' or 'python3')?

**Comment by sbc100** [comment]
Oops, I guess it was `python2`, can you retitle the step to something more general too?

**Comment by dschuff** [comment]
Brew says:
`Warning: python@3.9 3.9.13_1 is already installed and up-to-date.`
During runtime:
```
+ emcc -v
env: python: Permission denied
```
I'm not sure if that's the same error as before or not.

**Comment by dschuff** [comment]
hm, that is a very strange error from brew now.

**Comment by sbc100** [comment]
> hm, that is a very strange error from brew now.

ssh'ing in to take a look

**Comment by sbc100** [comment]
Man.. I can't figure out a good solution.. I guess we could just accept those old emscripten versions are not installable easily of macOS anymore?

**Comment by dschuff** [comment]
Is the problem that they're not installable easily, or that they're not easily runnable on the environment in Circle? Wouldn't just adding a symlink in the right place (easy for a user but maybe hard for a script that doesn't run as root) do the job?

**Comment by sbc100** [comment]
> Is the problem that they're not installable easily, or that they're not easily runnable on the environment in Circle? Wouldn't just adding a symlink in the right place (easy for a user but maybe hard for a script that doesn't run as root) do the job?

I can't seem to get python2 to install at all via homebrew.   At least not on the circleci instance. 

You could try symlinking python to python3 but the code that is looking for `python` is probably looking for python2.. e.g. it could contain `print` statements.. but I've not verfied if this is true.  python3 could suffice?

**Comment by dschuff** [comment]
I'd imagine the truly old version of emsdk really do need python2, no?

**Comment by sbc100** [comment]
> I'd imagine the truly old version of emsdk really do need python2, no?

I'm not sure.. IIRC its the just initial laucher that needs `python` in the path.. then it runs the actual emcc code using the embedded python

**Comment by sbc100** [comment]
You can `./emsdk install sdk-fastcomp-3b8cff670e9233a6623563add831647e8689a86b` to try it out.. I'll give it a go now

**Comment by sbc100** [comment]
```
#!/usr/bin/env python                                                           
                                                                                   
# This script should work in python 2 *or* 3. It loads the main code using         
# python_selector, which may pick a different version.                          
                                                                                
from tools import python_selector                                               
                                                                                
import sys                                                                      
                                                                                
if __name__ == '__main__':                                                      
  python_selector.run(__file__)      
```

I tried running it in python3 and it seems to work!    It does give some warnings but I think it should be ok for the purposes of the tests.

**Comment by dschuff** [comment]
That version seems to have py3 as its embedded python anyway

**Comment by dschuff** [comment]
I'll close this for now since we have #1103. Presumably we've just kicked the can down the road for a while.

**Pull request closed without merging**
