### PR TITLE
Add standard workdir for Dockerimage

### PR DESCRIPTION
**Pull request by trzecieu**
As requested by @curiousdannii in https://github.com/trzecieu/emscripten-docker/issues/58#issuecomment-648760800

### CODE REVIEW

**Comment by sbc100** [comment]
Does the directory exist in the image ?

**Comment by curiousdannii** [comment]
Docker will make the directory if it doesn't exist.

**Comment by trzecieu** [comment]
Hi @sbc100  - once I have an approval and checks are green - is it ok to merge? 
Is squashing preferable way to merge?

**Comment by sbc100** [comment]
Yes, please always squash and merge.

And if you get approval then, even if we gave comments, you are free to merge if you see fit.      If we have serious comments we will delay approval.

**Pull request merged**
