### PR TITLE
2.0.2

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Comment by kleisauke** [comment]
Perhaps https://github.com/emscripten-core/emsdk/pull/571/commits/1274e7a80b59afaf1856e14accfc72ee6baffcd6 should also be integrated (see https://github.com/emscripten-core/emsdk/pull/571) to ensure the `publish-docker-image` job passes?

**Comment by kripken** [comment]
@kleisauke - I don't know enough about that, so let's wait for @sbc100 , thanks for bringing this up!

**Comment by sbc100** [comment]
I landed #571 so maybe just rebase this change?

**Comment by kripken** [comment]
Sounds good, merged master + updated the commit (since stuff landed since yesterday).

**Pull request merged**
