### PR TITLE
Update emsdk for python 3 compatibility

### PR DESCRIPTION
**Pull request by choleraehyq**
* `filter` do not have method `__len__` in python 3.
* `HTTPMessage` do not have method `getheaders` in python 3.
* `sorted` do not have an argument `cmp` in python 3.
* type `basestring` has been removed in python 3.

### CODE REVIEW

**Comment by krux02** [comment]
I made this issue here: https://github.com/juj/emsdk/issues/59
I think your pull request would solve my issue, too. Even though I did not test it. So I my vote for this pull request.

**Comment by choleraehyq** [comment]
This PR is outdated, may not work. 
But I can update this PR and do essential tests if needed.

**Comment by krux02** [comment]
I would be interested, but I have no right to merge it.

**Comment by trzecieu** [comment]
This might be closed I believe, as some work has been done already:

**Comment by kripken** [comment]
Yes, I think we can close this. We also have tests for python3 now.

**Pull request closed without merging**
