### PR TITLE
3.1.17

### PR DESCRIPTION
**Pull request by aheejin**

### CODE REVIEW

**Comment by aheejin** [comment]
Hmm, c5763d20164d323645182148ec18d58f810d225a [failed](https://ci.chromium.org/ui/p/emscripten-releases/builders/ci/win/b8807981459635087185/overview) on Windows CI... I'll set the revision to the one before that.

**Comment by aheejin** [comment]
https://chromium.googlesource.com/emscripten-releases/+/19aab28a81be09863e86aba8ee4e20feaee31f6b passed the Emscripten CI on all platforms:
- Linux: https://ci.chromium.org/ui/p/emscripten-releases/builders/ci/linux/b8807982943146603985/overview
- Mac: https://ci.chromium.org/ui/p/emscripten-releases/builders/ci/mac/b8807982943620857793/overview
- Windows: https://ci.chromium.org/ui/p/emscripten-releases/builders/ci/win/b8807982942327135681/overview

Hmm, one thing, the corresponding Emscripten commit is https://github.com/emscripten-core/emscripten/commit/fbc532773d84d2bd7da876275671970e792ad1cd, whose main CI is not green, even though its corresponding PR's CI is green. The failure seems from a flaky browser test though: https://app.circleci.com/jobs/github/emscripten-core/emscripten/553254?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Do we care about this? Or should we wait for the next green commit? The reason I aimed for https://chromium.googlesource.com/emscripten-releases/+/19aab28a81be09863e86aba8ee4e20feaee31f6b is https://chromium.googlesource.com/emscripten-releases/+/c5763d20164d323645182148ec18d58f810d225a (the current latest commit)'s Windows CI fails for some reason which I don't know.

**Comment by sbc100** [comment]
Its fine to ignore know flake on the emscripten CI.. if you want you can re-try the chrome tests so it will be green :)

However, there is one step (that I guess is not document) we normally do when making a release.  We manually submit a PR to emscripten-releases like this https://chromium.googlesource.com/emscripten-releases/+/fb1baf00423818052359cf9126e94bc71c39feb5.  The commit consists of just copying DEPS to DEPS.tagged-release (where the DEPS file comes from the commit you want to use).  The commit will trigger the builder to produce an LTO build.

**Comment by sbc100** [comment]
You can then run `./scripts/create_release.py <LTO-sha> <non-LTO-sha>`

**Comment by dschuff** [comment]
Here's an LTO CL for 19aab28a81be09863e86aba8ee4e20feaee31f6b: https://chromium-review.googlesource.com/c/emscripten-releases/+/3781978

**Comment by aheejin** [comment]
@dschuff Thanks for the PR!

> You can then run `./scripts/create_release.py <LTO-sha> <non-LTO-sha>`

@sbc100 Done.

**Comment by aheejin** [comment]
Do we mandate the LTO release every time? The current https://github.com/emscripten-core/emsdk/blob/main/scripts/create_release.py picks a tot revision if a revision is not provided, but this automatic selection of tot does not provide an LTO release. If we mandate LTO release every time, do you think it would be clearer to remove that automatic selection option and ask the user to provide two SHAs (for both non-LTO and LTO builds)?

**Comment by dschuff** [comment]
We try to release with LTO every time, but there have been times when we've gone without it. I think in those cases the versioned name (e.g. `3.1.x`) would point to the non-LTO build and there just would not be a `3.1.x-asserts` build. I'm not sure whether or how `create-release.py` handles that though.

**Comment by aheejin** [comment]
@dschuff Yeah create-release.py handles it as you said. If we only do a non-LTO release that points to a version name and not an `-assert`. Our release process doc doesn't mention the LTO thing so I was slightly confused.

**Comment by aheejin** [comment]
Emscripten CI for https://github.com/emscripten-core/emscripten/commit/fbc532773d84d2bd7da876275671970e792ad1cd have succeeded: https://app.circleci.com/pipelines/github/emscripten-core/emscripten/22570/workflows/34930a30-67ca-45a1-917a-fea0db7b66a5/jobs/553811

I think all requirements have been met.

**Review by dschuff — APPROVED** [review]

**Comment by dschuff** [comment]
Yeah, I guess we should update the process doc for that.

**Comment by aheejin** [comment]
> Yeah, I guess we should update the process doc for that.

Tried that in emscripten-core/emscripten#17506.

**Pull request merged**
