### PR TITLE
Cleanup legacy 'copy_pregenerated_cache' handling. NFC.

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by sbc100** [comment]
I noticed the run_emcc thing and its comment were linked to the legacy cache copying stuff.

**Comment by sbc100** [comment]
ping.

**Comment by sbc100** [comment]
The CI does install `1.38.31` and `1.38.33`, but maybe we don't tests the cache pregeneration stuff with those old version.  I'll verify manually.

Having said that, if pre-copying the cache breaks for older version it still wouldn't actually stop anyone from working so ... at some point we should just remove this code maybe?

**Comment by kripken** [comment]
Good point. Yeah, seems fine to remove it eventually, at worst making very old versions slower isn't that bad.

**Comment by sbc100** [comment]
Tests with `1.39.10` and it still does the right thing,.

**Pull request merged**
