### PR TITLE
2.0.5

### PR DESCRIPTION
**Pull request by kripken**

### CODE REVIEW

**Review by sbc100 — APPROVED** [review]

**Comment by curiousdannii** [comment]
The Docker image increased by 181MB. Unfortunate.

**Comment by sbc100** [comment]
That is unexpected.  Can you tell what changed?

**Comment by curiousdannii** [comment]
It's the contents of the `/emsdk` folder. I haven't tried to look and see what has changed inside it.

**Comment by curiousdannii** [comment]
The biggest difference looks like 490MB (decompressed) in node_modules. And the big difference there is closure compiler (numbers are MB):

```
36	google-closure-compiler-osx
35	google-closure-compiler-windows
35	google-closure-compiler-linux
11	google-closure-compiler-java

288	google-closure-compiler-linux
273	google-closure-compiler-osx
40	google-closure-compiler-windows
10	google-closure-compiler-java
```

**Comment by sbc100** [comment]
I think that stuff is all downloaded after the emsdk bundle when we run `npm ci` as a post-install step.   Looks like maybe bug in the google-closure-compiler npm package?

**Comment by curiousdannii** [comment]
So between June and now the individual platform packages increased massively:
https://www.npmjs.com/package/google-closure-compiler-linux/v/20200614.0.0
https://www.npmjs.com/package/google-closure-compiler-linux/v/20200920.0.0

See https://github.com/google/closure-compiler-npm/issues/186

**Pull request merged**
