### PR TITLE
3.1.10

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by dschuff** [comment]
I think this build still has a broken ARM64 mac build. I haven't tested it (my M1 macbook is at home) but we're still using the same script as the last build and the test build I made, which were broken. So we probably shouldn't release this until we revert the switch to lld or disable LTO for arm64 mac (or maybe siwtch to full LTO instead).

**Comment by sbc100** [comment]
> I think this build still has a broken ARM64 mac build. I haven't tested it (my M1 macbook is at home) but we're still using the same script as the last build and the test build I made, which were broken. So we probably shouldn't release this until we revert the switch to lld or disable LTO for arm64 mac (or maybe siwtch to full LTO instead).

But isn't the current latest broken already in this way?

**Comment by dschuff** [comment]
Yes it is, so I think we should fix it before we ship another broken build :)

**Comment by sbc100** [comment]
> Yes it is, so I think we should fix it before we ship another broken build :)

Why link those two things.  This release doesn't make things better or worse for M1 users... since I've already invested a bunch of my time (and bot time) why not allow the release?  It doesn't effect M1 users does it?

**Comment by sbc100** [comment]
Updated to https://chromium.googlesource.com/emscripten-releases/+/8bd05c7221b4ce34d4bedec40b672d94e681a765

**Review by dschuff — APPROVED** [review]

**Pull request merged**
