### PR TITLE
Only upload node with gsutil in update_node.py if --upload is passed.

### PR DESCRIPTION
**Pull request by juj**
This allows running the script locally.

Is there some kind of automated script that needs a matching update, or was this always run manually?

### CODE REVIEW

**Comment by sbc100** [comment]
This script is always run manually.   I'm happy to run it if you need a new version uploaded.

**Review by sbc100 — COMMENTED** [review]
Is there any point in running this script if you don't then upload the binaries? 

i.e. the whole point of this script is to upload the binaries I think.   Are you imagining some other purpose?

**Comment by juj** [comment]
Yes, I can run the script locally to verify that the PR I am proposing to you works, even though I am not the one doing the uploads.

Without this PR, I could not verify that my addition of arm64 version of node would actually work, since in the inner loop it would abort running this script with an exception. update_python.py already had `--upload`, so having the same in `update_node.py` seems reasonable?

**Comment by sbc100** [comment]
In that case maybe you could call the new flag `-n/--try-run`?

**Review by sbc100 — APPROVED** [review]
Actually, since the python script already has that then this lgtm as is.

**Comment by juj** [comment]
> In that case maybe you could call the new flag `-n/--dry-run`?

I didn't see update_node.py having this flag.. so I monkeyed the same structure in update_node.py from update_python.py.

(I'll put up a PR to update python for ARM64 separately)

**Pull request merged**
