### PR TITLE
Remove Intel mac CircleCI configuration

### PR DESCRIPTION
**Pull request by dschuff**
Also switch bazel-mac to the arm64 config.
The CircleCI Intel mac config will be turned down soon.

### CODE REVIEW

**Comment by dschuff** [comment]
@walkingeyerobot will there need to be anything interesting done to bazel because of the architecture switch?

**Review by sbc100 — APPROVED** [review]

**Comment by dschuff** [comment]
Looks like the bazel test is failing on arm64 mac. The grep/sed pipeline that tries to set `VER` seems to be messing up (since `VER` ends up empty).

**Comment by dschuff** [comment]
So the `ggrep` version of grep is present and found... the pipeline just isn't correctly selecting the version.

**Comment by dschuff** [comment]
OK, just getting the version info from the file as JSON in Python seemed easier than debugging what was going wrong with grep. PTAL.
I decided against doing a bunch of error checking in the python file because in all the error cases I thought of, the messages I was thinking of writing were no better than the errors python itself would give directly, and would make the program 2x as long.

**Comment by dschuff** [comment]
also: do you have any idea why the "test-mac" and "test-bazel-mac" jobs are still showing up on the GH UI as "expected"? I thought I correctly got rid of them everywhere.

**Comment by sbc100** [comment]
The "expected" list of bots is set in the github branch settings for `main`.

**Review by sbc100 — APPROVED** [review]
This is where the `jq` tool would be awesome, but I'm not sure how hard it would be to ensure it is installed on all the bot.

**Comment by sbc100** [comment]
> `jq` appears to be available in Debian; if it's also in homebrew, I guess we could install it the same way we install other packages. Not sure if that's better or worse than a tiny python script. I guess at least with the python script, we can skip the homebrew step on the bazel bots entirely.

`jq` is like a really nice way to extract data from a json file.   I learned about it a couple of years back and I think if you work with json a lot its amazing.   I would totally make this python script redundant.   But not rush, either way is fine for now.

**Comment by allsey87** [comment]
@dschuff any idea why all PRs now have this pending test on `test-bazel-mac-arm64` that never starts?

**Comment by dschuff** [comment]
Hm, `test-bazel-mac-arm64` should be running on every PR now. Did you see this this on new PRs or for existing PRs that haven't had commits pushed since this PR landed?

**Comment by dschuff** [comment]
I guess you must be looking at #1405. I think if you push another commit it should work as expected with the new config. Otherwise if we just end up accepting the most recent commit there, we can just bypass the branch protections to land it, so no big deal either way.

**Pull request merged**
