### PR TITLE
Docker fixes and updates

### PR DESCRIPTION
**Pull request by ngaro**
- Dockerfile:
  - Use the most recent stable debian (buster) instead of the previous one
  - Build version 1.39.11 by default instead of 1.38.43
  - Fix small typo in the comments

- Makefile and README.MD: Fix incorrect name of image on dockerhub
(someone probably decided to change this without telling everyone)-

### CODE REVIEW

**Comment by kripken** [comment]
cc @trzecieu

**Comment by trzecieu** [comment]
Looks good! Thanks!

**Comment by kripken** [comment]
Great, thanks everyone!

**Comment by akoeplinger** [comment]
Is this published already? I don't see anything on https://hub.docker.com/u/emscripten/emsdk.

**Pull request merged**
