### PR TITLE
3.1.6

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Review by kripken — APPROVED** [review]
lgtm assuming the test error on the LTO run is a known issue?

https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8821392504803389793/+/u/Emscripten_testsuite__LTO_/stdout

**Comment by sbc100** [comment]
> lgtm assuming the test error on the LTO run is a known issue?
> 
> https://logs.chromium.org/logs/emscripten-releases/buildbucket/cr-buildbucket/8821392504803389793/+/u/Emscripten_testsuite__LTO_/stdout

Yes that is the intermitant flake of test_dylink_zlib which see from time to time and really should investigate

**Comment by kleisauke** [comment]
Was the 3.1.6 tag on this repository and the main repository intentionally not done?

**Comment by sbc100** [comment]
Sorry, done now.

**Pull request merged**
