### PR TITLE
Cleanup emsdk.py

### PR DESCRIPTION
**Pull request by sbc100**
- Remove some unneeded use of `global` keyword
- Use OrderedDict
- Add exit_with_error helper
- Remove SPIDERMONKY_ENGINE from emscripten config

### CODE REVIEW

**Comment by kripken** [comment]
Emscripten CI has broken ([ex1](https://circleci.com/gh/emscripten-core/emscripten/189042?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link), [ex2](https://circleci.com/gh/emscripten-core/emscripten/189034?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)). The breakage looks unrelated to anything on emscripten, and may be due to the `.emscripten` file and how it is used in the test suite.

This PR landed around the relevant time, and has some changes to `.emscripten`, so it's my only guess atm as to what could have changed things. @sbc100 is that possible?

cc @jgravelle-google who may already be investigating the breakage.

**Comment by kripken** [comment]
https://github.com/emscripten-core/emscripten/compare/fix2?expand=1 seems to confirm that this commit is the cause, as it uses the previous commit from the emsdk and gets past the `build*` stage error.

**Comment by sbc100** [comment]
Hmm, something to do with JS_ENGINES.. investigating

**Comment by sbc100** [comment]
Looks like it was removing the empty `V8_ENGINE = ''` from the config that was the problem.  I'm updating emscripten to deal with that better in the test code: https://github.com/emscripten-core/emscripten/pull/9597

Also, emscripten's circleci was depending on the `os` being imported in the config file, which I also removed in cases where it wasn't needed :(

**Pull request merged**
