### PR TITLE
2.0.28

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by dschuff** [comment]
I don't plan to make the LTO build the default because we haven't put llvm-link back into the LTO package to fix #866 yet

**Review by sbc100 — APPROVED** [review]

**Comment by sbc100** [comment]
I have a conflicting change.. should I wait for this? : https://github.com/emscripten-core/emsdk/pull/870

**Comment by dschuff** [comment]
Oh, interesting, I wonder which of these changes would be easier to rebase
on the other 🤣

**Comment by sbc100** [comment]
Happy for you to land this one.

**Comment by kleisauke** [comment]
It looks like the 2.0.28 tag is missing from https://github.com/emscripten-core/emsdk/tags (as a result, the `emscripten/emsdk:2.0.28` Docker image has not yet been published).

**Comment by dschuff** [comment]
Thanks, fixed.

**Pull request merged**
