### PR TITLE
2.0.24

### PR DESCRIPTION
**Pull request by sbc100**

### CODE REVIEW

**Comment by dschuff** [comment]
Should we do this one as LTO?

**Comment by sbc100** [comment]
Did we manage to get any feedback on the last LTO release?

I guess there any issues that come up we can immediately release 2.0.25?   

I guess we can/should trigger and LTO build in any case?

**Comment by dschuff** [comment]
Yes, in any case, https://chromium-review.googlesource.com/c/emscripten-releases/+/2945802

We got feedback that it worked and they were able to compile. No feedback on performance, but not surprises either. Probably good enough.

**Comment by sbc100** [comment]
Sounds good to me.  Does that mean we should abandon this PR and wait for the LTO build?  Or at least abandon this once the LTO build is released?

**Comment by kripken** [comment]
The LTO builds are larger, though - perhaps we should measure the size/speed tradeoff first? E.g. if it makes the emscripten test suite on CI here faster that would be very compelling I think.

**Comment by dschuff** [comment]
The emscripten test suite here always uses `tot` doesn't it? In that case only the few CI runs that happen to start between the LTO build and the next build would get it.

**Comment by kripken** [comment]
Oh, right... nevermind that idea then.

**Comment by sbc100** [comment]
Actually I think we need to wait until https://github.com/emscripten-core/emscripten/pull/14403 rolls in to tag a release.

**Pull request closed without merging**
