### PR TITLE
Add Visual Studio 2017 support

### PR DESCRIPTION
**Pull request by RReverser**
Added support for Visual Studio 2017.

Tested locally, including with clean environment (no VS variables), everything seems to be building smoothly.

### CODE REVIEW

**Comment by RReverser** [comment]
Looks like my editor auto-removed trailing whitespaces, so diff looks slightly more dirty than it should, but that's probably for the best? Let me know if you would prefer to keep these trailing spaces for some reason.

**Comment by RReverser** [comment]
@juj Please let me know if there's anything to be fixed/changed here.

**Comment by juj** [comment]
Very sorry about the delay here. This is great work, but I have not found the time to first hand verify by installing VS2017 to make this work. I'm trying to up the priority here, just recently got a new laptop where installing VS2017 is now prime time.

**Comment by RReverser** [comment]
I guess this one doesn't matter anymore now that newer one is merged?

**Comment by trzecieu** [comment]
Close as obsolete?

**Pull request closed without merging**
